owner: tyrepharm
repo: upptime

sites:
  - name: Tyre Pharmacy
    url: https://tyrepharm.ru/
  - name: Doshipui
    url: https://xn--d1aidsgy6a.xn--p1ai/
  - name: Monitor / MySQL 
    url: https://tyrepharm.ru/local/api/Monitor/db
    headers:
      - "Content-Type: application/json"
  - name: Monitor / init.php 
    url: https://tyrepharm.ru/local/api/Monitor/init
    headers:
      - "Content-Type: application/json"
  - name: Monitor / init.php 
    url: https://tyrepharm.ru/local/api/Monitor/services
    headers:
      - "Content-Type: application/json"

status-website:
  baseUrl: /upptime
  name: Upptime
  logoUrl: https://tyrepharm.ru/upload/aspro.mshop/145/14547cf839786595aaf89f08fb31a9ca.svg
  # navbar:
  #   - title: Status
  #     href: /upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
