owner: tyrepharm
repo: upptime

sites:
  - name: Tyre Pharmacy
    url: https://tyrepharm.ru/
  - name: Doshipui
    url: https://xn--d1aidsgy6a.xn--p1ai/

status-website:
  baseUrl: /upptime
  name: Upptime
  navbar:
    - title: Status
      href: /upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
